const pokemonlist = [
    {
        _id:1.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/2/21/001Bulbasaur.png/250px-001Bulbasaur.png",
        name:"Bulbasaur",
        type:"Grass, Poison",
        description:"Bulbasaur is a dualtype Grass/Poison Pokémon introduced in Generation I. It evolves into Ivysaur starting at level 16, which evolves into Venusaur starting at level 32. Along with Charmander and Squirtle, Bulbasaur is one of three starter Pokémon of Kanto available at the beginning of Pokémon Red, Green, Blue, FireRed, and LeafGreen.",
        keywords:["Bulbassauro","Bulbasaur"]},
    {
        _id:2.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/7/73/002Ivysaur.png/250px-002Ivysaur.png",
        name:"Ivysaur",
        type:"Grass, Poison",
        description:"Ivysaur is a dual-type Grass/Poison Pokémon introduced in Generation I. It evolves from Bulbasaur starting at level 16 and evolves into Venusaur starting at level 32.",
        keywords:["Ivissauro","Ivyssauro","Ivysaur"]},
    {
        _id:3.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/a/ae/003Venusaur.png/250px-003Venusaur.png",
        name:"Venusaur",
        type:"Grass, Poison",
        description:"Venusaur is a dual-type Grass/Poison Pokémon introduced in Generation I. It evolves from Ivysaur starting at level 32. It is the final form of Bulbasaur. It can Mega Evolve into Mega Venusaur using the Venusaurite. Venusaur is the game mascot of both Green and LeafGreen, appearing on the boxart of both.",
        keywords:["Venossauro","Venussauro","Venusaur"]},
    {
        _id:4.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/7/73/004Charmander.png/250px-004Charmander.png",
        name:"Charmander",
        type:"Fire",
        description:"Charmander is a Fire-type Pokémon introduced in Generation I. It evolves into Charmeleon starting at level 16, which evolves into Charizard starting at level 36. Along with Bulbasaur and Squirtle, Charmander is one of three starter Pokémon of Kanto available at the beginning of Pokémon Red, Green, Blue, FireRed, and LeafGreen.",
        keywords:["Charmander"]},
    {
        _id:5.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/4/4a/005Charmeleon.png/250px-005Charmeleon.png",
        name:"Charmeleon",
        type:"Fire",
        description:"Charmeleon is a Fire-type Pokémon introduced in Generation I. It evolves from Charmander starting at level 16 and evolves into Charizard starting at level 36.",
        keywords:["Charmeleon"]},
    {
        _id:6.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/7/7e/006Charizard.png/250px-006Charizard.png",
        name:"Charizard",
        type:"Fire, Flying",
        description:"Charizard is a dual-type Fire/Flying Pokémon introduced in Generation I. It evolves from Charmeleon starting at level 36. It is the final form of Charmander. It can Mega Evolve into two forms: Mega Charizard X using Charizardite X and Mega Charizard Y using Charizardite Y. Charizard is the game mascot of Pokémon Red and FireRed Versions.",
        keywords:["Charizard"]},
    {
        _id:7.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/3/39/007Squirtle.png/250px-007Squirtle.png",
        name:"Squirtle",
        type:"Water",
        description:"Squirtle is a Water-type Pokémon introduced in Generation I. It evolves into Wartortle starting at level 16, which evolves into Blastoise starting at level 36. Along with Bulbasaur and Charmander, Squirtle is one of three starter Pokémon of Kanto available at the beginning of Pokémon Red, Green, Blue, FireRed, and LeafGreen.",
        keywords:["Squirtle"]},
    {
        _id:8.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/0/0c/008Wartortle.png/250px-008Wartortle.png",
        name:"Wartortle",
        type:"Water",
        description:"Wartortle is a Water-type Pokémon introduced in Generation I. It evolves from Squirtle starting at level 16 and evolves into Blastoise starting at level 36.",
        keywords:["Wartortle"]},
    {
        _id:9.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/0/02/009Blastoise.png/250px-009Blastoise.png",
        name:"Blastoise",
        type:"Water",
        description:"Blastoise is a Water-type Pokémon introduced in Generation I. It evolves from Wartortle starting at level 36. It is the final form of Squirtle. It can Mega Evolve into Mega Blastoise using the Blastoisinite. Blastoise is the game mascot of the Japanese and international versions of Pokémon Blue, appearing on the boxart of both.",
        keywords:["Blastoise"]},
    {
        _id:10.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/5/5d/010Caterpie.png/250px-010Caterpie.png",
        name:"Caterpie",
        type:"Bug",
        description:"Caterpie is a Bug-type Pokémon introduced in Generation I. It evolves into Metapod starting at level 7, which evolves into Butterfree starting at level 10.",
        keywords:["Caterpie"]},
    {
        _id:11.0,
        photo:"https://cdn.bulbagarden.net/upload/c/cd/011Metapod.png",
        name:"Metapod",
        type:"Bug",
        description:"Metapod is a Bug-type Pokémon introduced in Generation I. It evolves from Caterpie starting at level 7 and evolves into Butterfree starting at level 10.",
        keywords:["Metapod"]},
    {
        _id:12.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/d/d1/012Butterfree.png/250px-012Butterfree.png",
        name:"Butterfree",
        type:"Bug, Flying",
        description:"Butterfree is a dual-type Bug/Flying Pokémon introduced in Generation I. It evolves from Metapod starting at level 10. It is the final form of Caterpie.",
        keywords:["Butterfree","Butterfly"]},
    {
        _id:13.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/d/df/013Weedle.png/250px-013Weedle.png",
        name:"Weedle",
        type:"Bug, Poison",
        description:"Weedle is a dual-type Bug/Poison Pokémon introduced in Generation I. It evolves into Kakuna starting at level 7, which evolves into Beedrill starting at level 10.",
        keywords:["Weedle"]},
    {
        _id:14.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/f/f0/014Kakuna.png/250px-014Kakuna.png",
        name:"Kakuna",
        type:"Bug, Poison",
        description:"Kakuna is a dual-type Bug/Poison Pokémon introduced in Generation I. It evolves from Weedle starting at level 7 and evolves into Beedrill starting at level 10.",
        keywords:["Kakuna"]},
    {
        _id:15.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/6/61/015Beedrill.png/250px-015Beedrill.png",
        name:"Beedrill",
        type:"Bug, Poison",
        description:"Beedrill is a dual-type Bug/Poison Pokémon introduced in Generation I. It evolves from Kakuna starting at level 10. It is the final form of Weedle. It can Mega Evolve into Mega Beedrill using the Beedrillite.",
        keywords:["Beedrill"]},
    {
        _id:16.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/5/55/016Pidgey.png/250px-016Pidgey.png",
        name:"Pidgey",
        type:"Normal, Flying",
        description:"Pidgey is a dual-type Normal/Flying Pokémon introduced in Generation I. It evolves into Pidgeotto starting at level 18, which evolves into Pidgeot starting at level 36.",
        keywords: ["Pidgey"]},
    {
        _id:17.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/7/7a/017Pidgeotto.png/250px-017Pidgeotto.png",
        name:"Pidgeotto",
        type:"Normal, Flying",
        description:"Pidgeotto is a dual-type Normal/Flying Pokémon introduced in Generation I. It evolves from Pidgey starting at level 18 and evolves into Pidgeot starting at level 36.",
        keywords:["Pidgeotto","Pidgeoto"]},
    {
        _id:18.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/5/57/018Pidgeot.png/250px-018Pidgeot.png",
        name:"Pidgeot",
        type:"Normal, Flying",
        description:"Pidgeot is a dual-type Normal/Flying Pokémon introduced in Generation I. It evolves from Pidgeotto starting at level 36. It is the final form of Pidgey. It can Mega Evolve into Mega Pidgeot using the Pidgeotite.",
        keywords:["Pidgeot"]},
    {
        _id:19.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/4/46/019Rattata.png/250px-019Rattata.png",
        name:"Rattata",
        type:"Normal",
        description:"Rattata is a Normal-type Pokémon introduced in Generation I. It evolves into Raticate starting at level 20. In Alola, Rattata has a regional variant that is Dark/Normal. It evolves into Alolan Raticate when leveled up at night starting at level 20. It is the only possible starter Pokémon in Pokémon Rumble.",
        keywords:["Rattata","Ratata","Ratatta"]},
    {
        _id:20.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/f/f4/020Raticate.png/250px-020Raticate.png",
        name:"Raticate",
        type:"Normal",
        description:"Raticate is a Normal-type Pokémon introduced in Generation I. It evolves from Rattata starting at level 20. In Alola, Raticate has a regional variant that is Dark/Normal. It evolves from Alolan Rattata when leveled up at night starting at level 20.",
        keywords:["Raticate"]},
    {
        _id:21.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/8/8b/021Spearow.png/250px-021Spearow.png",
        name:"Spearow",
        type:"Normal, Flying",
        description:"Spearow is a dual-type Normal/Flying Pokémon introduced in Generation I. It evolves into Fearow starting at level 20.",
        keywords:["Spearow"]},
    {
        _id:22.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/a/a0/022Fearow.png/250px-022Fearow.png",
        name:"Fearow",
        type:"Normal, Flying",
        description:"Fearow is a dual-type Normal/Flying Pokémon introduced in Generation I. It evolves from Spearow starting at level 20.",
        keywords:["Fearow"]},
    {
        _id:23.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/f/fa/023Ekans.png/250px-023Ekans.png",
        name:"Ekans",
        type:"Poison",
        description:"Ekans is a Poison-type Pokémon introduced in Generation I. It evolves into Arbok starting at level 22.",
        keywords:["Ekans"]},
    {
        _id:24.0,
        photo:"https://cdn.bulbagarden.net/upload/c/cd/024Arbok.png",
        name:"Arbok",
        type:"Poison",
        description:"Arbok is a Poison-type Pokémon introduced in Generation I. It evolves from Ekans starting at level 22.",
        keywords:["Arbok"]},
    {
        _id:25.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/0/0d/025Pikachu.png/250px-025Pikachu.png",
        name:"Pikachu",
        type:"Electric",
        description:"Pikachu is an Electric-type Pokémon introduced in Generation I. It evolves from Pichu when leveled up with high friendship and evolves into Raichu when exposed to a Thunder Stone. However, the starter Pikachu in Pokémon Yellow will refuse to evolve into Raichu unless it is traded and evolved on another save file. In Alola, Pikachu will evolve into Alolan Raichu when exposed to a Thunder Stone. Pikachu is popularly known as the mascot of the Pokémon franchise and a major representative of Nintendo's collective mascots. It is also the game mascot and starter Pokémon of Pokémon Yellow and Pokémon: Let's Go, Pikachu!. It has made numerous appearances on the boxes of spin-off titles. Pikachu is also the starter Pokémon in Pokémon Rumble Blast and Pokémon Rumble World.",
        keywords:["Pikachu"]},
    {
        _id:26.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/8/88/026Raichu.png/250px-026Raichu.png",
        name:"Raichu",
        type:"Electric",
        description:"Raichu is an Electric-type Pokémon introduced in Generation I. It evolves from Pikachu when exposed to a Thunder Stone. It is the final form of Pichu. In Alola, Raichu has a regional variant that is Electric/Psychic. It evolves from Pikachu when exposed to a Thunder Stone. All Pikachu in Alola will evolve into this form regardless of their origin.",
        keywords:["Raichu"]},
    {
        _id:27.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/9/9e/027Sandshrew.png/250px-027Sandshrew.png",
        name:"Sandshrew",
        type:"Ground",
        description:"Sandshrew is a Ground-type Pokémon introduced in Generation I. It evolves into Sandslash starting at level 22. In Alola, Sandshrew has a regional variant that is Ice/Steel. It evolves into Alolan Sandslash when exposed to an Ice Stone.",
        keywords:["Sandshrew"]},
    {
        _id:28.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/0/0b/028Sandslash.png/250px-028Sandslash.png",
        name:"Sandslash",
        type:"Ground",
        description:"Sandslash is a Ground-type Pokémon introduced in Generation I. It evolves from Sandshrew starting at level 22. In Alola, Sandslash has a regional variant that is Ice/Steel. It evolves from Alolan Sandshrew when exposed to an Ice Stone.",
        keywords:["Sandslash"]},
    {
        _id:29.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/8/81/029Nidoran.png/250px-029Nidoran.png",
        name:"Nidoran♀",
        type:"Poison",
        description:"Nidoran♀ is a Poison-type Pokémon introduced in Generation I. It evolves into Nidorina starting at level 16, which evolves into Nidoqueen when exposed to a Moon Stone. It is related to the Nidoran♂ line, and can produce Eggs that contain either Nidoran♀ or Nidoran♂. However, it is the only one of its line that can breed, as Nidorina and Nidoqueen are part of the Undiscovered Egg Group.",
        keywords:["Nidoran F","NidoranF","Female Nidoran","Nidoran Fêmea"]},
    {
        _id:30.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/c/cd/030Nidorina.png/250px-030Nidorina.png",
        name:"Nidorina",
        type:"Poison",
        description:"Nidorina is a Poison-type Pokémon introduced in Generation I. It evolves from Nidoran♀ starting at level 16 and evolves into Nidoqueen when exposed to a Moon Stone. It is related to the Nidoran♂ line, but unlike Nidoran♀, Nidorina cannot breed.",
        keywords:["Nidorina"]},
    {
        _id:31.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/b/bf/031Nidoqueen.png/250px-031Nidoqueen.png",
        name:"Nidoqueen",
        type:"Poison, Ground",
        description:"Nidoqueen is a dual-type Poison/Ground Pokémon introduced in Generation I. It evolves from Nidorina when exposed to a Moon Stone. It is the final form of Nidoran♀. It is related to the Nidoran♂ line, but unlike Nidoran♀, Nidoqueen cannot breed.",
        keywords:["Nidoqueen"]},
    {
        _id:32.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/4/4a/032Nidoran.png/250px-032Nidoran.png",
        name:"Nidoran♂",
        type:"Poison",
        description:"Nidoran♂ is a Poison-type Pokémon introduced in Generation I. It evolves into Nidorino starting at level 16, which evolves into Nidoking when exposed to a Moon Stone. It is related to Nidoran♀ and, starting in Generation V, can produce Eggs that contain either Nidoran♂ or Nidoran♀ when bred with Ditto.",
        keywords:["Nidoran M","NidoranM","Male Nidoran","Nidoran Macho"]},
    {
        _id:33.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/9/9f/033Nidorino.png/250px-033Nidorino.png",
        name:"Nidorino",
        type:"Poison",
        description:"Nidorino is a Poison-type Pokémon introduced in Generation I. It evolves from Nidoran♂ starting at level 16 and evolves into Nidoking when exposed to a Moon Stone. It is related to Nidoran♀ and, starting in Generation V, can produce Eggs that contain either Nidoran♂ or Nidoran♀ when bred with Ditto.",
        keywords:["Nidorino"]},
    {
        _id:34.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/c/c6/034Nidoking.png/250px-034Nidoking.png",
        name:"Nidoking",
        type:"Poison, Ground",
        description:"Nidoking is a dual-type Poison/Ground Pokémon introduced in Generation I. It evolves from Nidorino when exposed to a Moon Stone. It is the final form of Nidoran♂. It is related to Nidoran♀ and, starting in Generation V, can produce Eggs that contain either Nidoran♂ or Nidoran♀ when bred with Ditto.",
        keywords:["Nidoking"]},
    {
        _id:35.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/f/f4/035Clefairy.png/250px-035Clefairy.png",
        name:"Clefairy",
        type:"Fairy",
        description:"Clefairy is a Fairy-type Pokémon introduced in Generation I. Prior to Generation VI, it was a Normal-type Pokémon. It evolves from Cleffa when leveled up with high friendship and evolves into Clefable when exposed to a Moon Stone.",
        keywords:["Clefairy"]},
    {
        _id:36.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/a/a9/036Clefable.png/250px-036Clefable.png",
        name:"Clefable",
        type:"Fairy",
        description:"Clefable is a Fairy-type Pokémon introduced in Generation I. Prior to Generation VI, it was a Normal-type Pokémon. It evolves from Clefairy when exposed to a Moon Stone. It is the final form of Cleffa.",
        keywords:["Clefable"]},
    {
        _id:37.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/6/60/037Vulpix.png/250px-037Vulpix.png",
        name:"Vulpix",
        type:"Fire",
        description:"Vulpix is a Fire-type Pokémon introduced in Generation I. It evolves into Ninetales when exposed to a Fire Stone. In Alola, Vulpix has an Ice-type regional variant. It evolves into Alolan Ninetales when exposed to an Ice Stone",
        keywords:["Vulpix"]},
    {
        _id:38.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/0/05/038Ninetales.png/250px-038Ninetales.png",
        name:"Ninetales",
        type:"Fire",
        description:"Ninetales is a Fire-type Pokémon introduced in Generation I. It evolves from Vulpix when exposed to a Fire Stone. In Alola, Ninetales has a regional variant that is Ice/Fairy. It evolves from Alolan Vulpix when exposed to an Ice Stone.",
        keywords:["Ninetales"]},
    {
        _id:39.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/3/3e/039Jigglypuff.png/250px-039Jigglypuff.png",
        name:"Jigglypuff",
        type:"Normal, Fairy",
        description:"Jigglypuff is a dual-type Normal/Fairy Pokémon introduced in Generation I. Prior to Generation VI, it was a pure Normal-type Pokémon. It evolves from Igglybuff when leveled up with high friendship and evolves into Wigglytuff when exposed to a Moon Stone.",
        keywords:["Jigglypuff"]},
    {
        _id:40.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/9/92/040Wigglytuff.png/250px-040Wigglytuff.png",
        name:"Wigglytuff",
        type:"Normal, Fairy",
        description:"Wigglytuff is a dual-type Normal/Fairy Pokémon introduced in Generation I. Prior to Generation VI, it was a pure Normal-type Pokémon. It evolves from Jigglypuff when exposed to a Moon Stone. It is the final form of Igglybuff.",
        keywords:["Wigglytuff"]},
    {
        _id:41.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/d/da/041Zubat.png/250px-041Zubat.png",
        name:"Zubat",
        type:"Poison, Flying",
        description:"Zubat is a dual-type Poison/Flying Pokémon introduced in Generation I. It evolves into Golbat starting at level 22, which evolves into Crobat when leveled up with high friendship.",
        keywords:["Zubat"]},
    {
        _id:42.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/0/0c/042Golbat.png/250px-042Golbat.png",
        name:"Golbat",
        type:"Poison, Flying",
        description:"Golbat is a dual-type Poison/Flying Pokémon introduced in Generation I. It evolves from Zubat starting at level 22 and evolves into Crobat when leveled up with high friendship.",
        keywords:["Golbat"]},
    {
        _id:43.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/4/43/043Oddish.png/250px-043Oddish.png",
        name:"Oddish",
        type:"Grass, Poison",
        description:"Oddish is a dual-type Grass/Poison Pokémon introduced in Generation I. It evolves into Gloom starting at level 21, which evolves into Vileplume when exposed to a Leaf Stone or into Bellossom when exposed to a Sun Stone.",
        keywords:["Oddish","Odish"]},
    {
        _id:44.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/2/2a/044Gloom.png/250px-044Gloom.png",
        name:"Gloom",
        type:"Grass, Poison",
        description:"Gloom is a dual-type Grass/Poison Pokémon introduced in Generation I. It evolves from Oddish at level 21 and evolves into either Vileplume when exposed to a Leaf Stone or Bellossom when exposed to a Sun Stone.",
        keywords:["Gloom","Gloon"]},
    {
        _id:45.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/6/6a/045Vileplume.png/250px-045Vileplume.png",
        name:"Vileplume",
        type:"Grass, Poison",
        description:"Vileplume is a dual-type Grass/Poison Pokémon introduced in Generation I. It evolves from Gloom when exposed to a Leaf Stone. It is one of Oddish's final forms, the other being Bellossom.",
        keywords:["Vileplume"]},
    {
        _id:46.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/d/d4/046Paras.png/250px-046Paras.png",
        name:"Paras",
        type:"Bug, Grass",
        description:"Paras is a dual-type Bug/Grass Pokémon introduced in Generation I. It evolves into Parasect starting at level 24.",
        keywords:["Paras"]},
    {
        _id:47.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/8/80/047Parasect.png/250px-047Parasect.png",
        name:"Parasect",
        type:"Bug, Grass",
        description:"Parasect is a dual-type Bug/Grass Pokémon introduced in Generation I. It evolves from Paras starting at level 24.",
        keywords:["Parasect"]},
    {
        _id:48.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/a/ad/048Venonat.png/250px-048Venonat.png",
        name:"Venonat",
        type:"Bug, Poison",
        description:"Venonat is a dual-type Bug/Poison Pokémon introduced in Generation I. It evolves into Venomoth starting at level 31.",
        keywords:["Venonat"]},
    {
        _id:49.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/d/d3/049Venomoth.png/250px-049Venomoth.png",
        name:"Venomoth",
        type:"Bug, Poison",
        description:"Venomoth is a dual-type Bug/Poison Pokémon introduced in Generation I. It evolves from Venonat starting at level 31.",
        keywords:["Venomoth"]},
    {
        _id:50.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/3/31/050Diglett.png/250px-050Diglett.png",
        name:"Diglett",
        type:"Ground",
        description:"Diglett is a Ground-type Pokémon introduced in Generation I. It evolves into Dugtrio starting at level 26. In Alola, Diglett has a regional variant that is Ground/Steel. It evolves into Alolan Dugtrio starting at level 26.",
        keywords:["Diglett","Diglet"]},
    {
        _id:51.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/e/e5/051Dugtrio.png/250px-051Dugtrio.png",
        name:"Dugtrio",
        type:"Ground",
        description:"Dugtrio is a Ground-type Pokémon introduced in Generation I. It evolves from Diglett starting at level 26. In Alola, Dugtrio has a regional variant that is Ground/Steel. It evolves from Alolan Diglett starting at level 26.",
        keywords:["Dugtrio"]},
    {
        _id:52.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/d/d6/052Meowth.png/250px-052Meowth.png",
        name:"Meowth",
        type:"Normal",
        description:"Meowth is a Normal-type Pokémon introduced in Generation I. It evolves into Persian starting at level 28. In Alola, Meowth has a regional variant that is Dark-type. It evolves into Alolan Persian when leveled up with high friendship.",
        keywords:["Meowth","Miau"]},
    {
        _id:53.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/1/13/053Persian.png/250px-053Persian.png",
        name:"Persian",
        type:"Normal",
        description:"Persian is a Normal-type Pokémon introduced in Generation I. It evolves from Meowth starting at level 28. In Alola, Persian has a regional variant that is Dark-type. It evolves from Alolan Meowth when leveled up with high friendship.",
        keywords:["Persian","Persa"]},
    {
        _id:54.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/5/53/054Psyduck.png/250px-054Psyduck.png",
        name:"Psyduck",
        type:"Water",
        description:"Psyduck is a Water-type Pokémon introduced in Generation I. It evolves into Golduck starting at level 33.",
        keywords:["Psyduck"]},
    {
        _id:55.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/f/fe/055Golduck.png/250px-055Golduck.png",
        name:"Golduck",
        type:"Water",
        description:"Golduck is a Water-type Pokémon introduced in Generation I. It evolves from Psyduck starting at level 33.",
        keywords:["Golduck"]},
    {
        _id:56.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/4/41/056Mankey.png/250px-056Mankey.png",
        name:"Mankey",
        type:"Fighting",
        description:"Mankey is a Fighting-type Pokémon introduced in Generation I. It evolves into Primeape starting at level 28.",
        keywords:["Mankey","Monkey"]},
    {
        _id:57.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/9/9a/057Primeape.png/250px-057Primeape.png",
        name:"Primeape",
        type:"Fighting",
        description:"Primeape is a Fighting-type Pokémon introduced in Generation I. It evolves from Mankey starting at level 28.",
        keywords:["Primeape"]},
    {
        _id:58.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/3/3d/058Growlithe.png/250px-058Growlithe.png",
        name:"Growlithe",
        type:"Fire",
        description:"Growlithe is a Fire-type Pokémon introduced in Generation I. It evolves into Arcanine when exposed to a Fire Stone.",
        keywords:["Growlithe","Growlith"]},
    {
        _id:59.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/b/b8/059Arcanine.png/250px-059Arcanine.png",
        name:"Arcanine",
        type:"Fire",
        description:"Arcanine is a Fire-type Pokémon introduced in Generation I. It evolves from Growlithe when exposed to a Fire Stone.",
        keywords:["Arcanine"]},
    {
        _id:60.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/4/49/060Poliwag.png/250px-060Poliwag.png",
        name:"Poliwag",
        type:"Water",
        description:"Poliwag is a Water-type Pokémon introduced in Generation I. It evolves into Poliwhirl starting at level 25, which evolves into Poliwrath when exposed to a Water Stone or into Politoed when traded holding a King's Rock.",
        keywords:["Poliwag"]},
    {
        _id:61.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/a/a9/061Poliwhirl.png/250px-061Poliwhirl.png",
        name:"Poliwhirl",
        type:"Water",
        description:"Poliwhirl is a Water-type Pokémon introduced in Generation I. It evolves from Poliwag starting at level 25. It evolves into Poliwrath when exposed to a Water Stone or Politoed when traded holding a King's Rock.",
        keywords:["Poliwhirl"]},
    {
        _id:62.0,
        photo:"https://cdn.bulbagarden.net/upload/2/2d/062Poliwrath.png",
        name:"Poliwrath",
        type:"Ground",
        description:"Poliwrath is a dual-type Water/Fighting Pokémon introduced in Generation I. It evolves from Poliwhirl when exposed to a Water Stone. It is one of Poliwag's final forms, the other being Politoed.",
        keywords:["Poliwrath"]},
    {
        _id:63.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/6/62/063Abra.png/250px-063Abra.png",
        name:"Abra",
        type:"Psychic",
        description:"Abra is a Psychic-type Pokémon introduced in Generation I. It evolves into Kadabra starting at level 16, which evolves into Alakazam when traded.",
        keywords:["Abra"]},
    {
        _id:64.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/9/97/064Kadabra.png/250px-064Kadabra.png",
        name:"Kadabra",
        type:"Psychic",
        description:"Kadabra is a Psychic-type Pokémon introduced in Generation I. It evolves from Abra starting at level 16 and evolves into Alakazam when traded. From Generation IV onward, a Kadabra holding an Everstone will still evolve when traded between games.",
        keywords:["Kadabra"]},
    {
        _id:65.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/c/cc/065Alakazam.png/250px-065Alakazam.png",
        name:"Alakazam",
        type:"Psychic",
        description:"Alakazam is a Psychic-type Pokémon introduced in Generation I. It evolves from Kadabra when traded. It is the final form of Abra. It can Mega Evolve into Mega Alakazam using the Alakazite.",
        keywords:["Alakazam","Alakazan"]},
    {
        _id:66.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/8/85/066Machop.png/250px-066Machop.png",
        name:"Machop",
        type:"Fighting",
        description:"Machop is a Fighting-type Pokémon introduced in Generation I. It evolves into Machoke starting at level 28, which evolves into Machamp when traded.",
        keywords:["Machop"]},
    {
        _id:67.0,
        photo:"https://cdn.bulbagarden.net/upload/8/8e/067Machoke.png",
        name:"Machoke",
        type:"Fighting",
        description:"Machoke is a Fighting-type Pokémon introduced in Generation I. It evolves from Machop starting at level 28 and evolves into Machamp when traded.",
        keywords:["Machoke"]},
    {
        _id:68.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/8/8f/068Machamp.png/250px-068Machamp.png",
        name:"Machamp",
        type:"Fighting",
        description:"Machamp is a Fighting-type Pokémon introduced in Generation I. It evolves from Machoke when traded. It is the final form of Machop.",
        keywords:["Machamp"]},
    {
        _id:69.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/a/a2/069Bellsprout.png/250px-069Bellsprout.png",
        name:"Bellsprout",
        type:"Grass, Poison",
        description:"Bellsprout is a dual-type Grass/Poison Pokémon introduced in Generation I. It evolves into Weepinbell starting at level 21, which evolves into Victreebel when exposed to a Leaf Stone.",
        keywords:["Bellsprout"]},
    {
        _id:70.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/9/9f/070Weepinbell.png/250px-070Weepinbell.png",
        name:"Weepinbell",
        type:"Grass, Poison",
        description:"Weepinbell is a dual-type Grass/Poison Pokémon introduced in Generation I. It evolves from Bellsprout starting at level 21 and evolves into Victreebel when exposed to a Leaf Stone.",
        keywords:["Weepinbell"]},
    {
        _id:71.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/b/be/071Victreebel.png/250px-071Victreebel.png",
        name:"Victreebel",
        type:"Grass, Poison",
        description:"Victreebel is a dual-type Grass/Poison Pokémon introduced in Generation I. It evolves from Weepinbell when exposed to a Leaf Stone. It is the final form of Bellsprout.",
        keywords:["Victreebel","Victrebel"]},
    {
        _id:72.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/4/4e/072Tentacool.png/250px-072Tentacool.png",
        name:"Tentacool",
        type:"Water, Poison",
        description:"Tentacool is a dual-type Water/Poison Pokémon introduced in Generation I. It evolves into Tentacruel starting at level 30."
        ,keywords:["Tentacool"]},
    {
        _id:73.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/f/f6/073Tentacruel.png/250px-073Tentacruel.png",
        name:"Tentacruel",
        type:"Water, Poison",
        description:"Tentacruel is a dual-type Water/Poison Pokémon introduced in Generation I. It evolves from Tentacool starting at level 30"
        ,keywords:["Tentacruel"]},
    {
        _id:74.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/9/98/074Geodude.png/250px-074Geodude.png",
        name:"Geodude",
        type:"Rock, Ground",
        description:"Geodude is a dual-type Rock/Ground Pokémon introduced in Generation I. It evolves into Graveler starting at level 25, which evolves into Golem when traded. In Alola, Geodude has a regional variant that is Rock/Electric. It evolves into Alolan Graveler starting at level 25, which evolves into Alolan Golem when traded.",
        keywords:["Geodude"]},
    {
        _id:75.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/7/75/075Graveler.png/250px-075Graveler.png",
        name:"Graveler",
        type:"Rock, Ground",
        description:"Graveler is a dual-type Rock/Ground Pokémon introduced in Generation I. It evolves from Geodude starting at level 25 and evolves into Golem when traded. In Alola, Graveler has a regional variant that is Rock/Electric. It evolves from Alolan Geodude starting at level 25 and evolves into Alolan Golem when traded.",
        keywords:["Graveler"]},
    {
        _id:76.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/f/f2/076Golem.png/250px-076Golem.png",
        name:"Golem",
        type:"Rock, Ground",
        description:"Golem is a dual-type Rock/Ground Pokémon introduced in Generation I. It evolves from Graveler when traded. It is the final form of Geodude. In Alola, Golem has a regional variant that is Rock/Electric. It evolves from Alolan Graveler when traded. It is the final form of Alolan Geodude.",
        keywords:["Golem"]},
    {
        _id:77.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/3/3b/077Ponyta.png/250px-077Ponyta.png",
        name:"Ponyta",
        type:"Fire",
        description:"Ponyta is a Fire-type Pokémon introduced in Generation I. It evolves into Rapidash starting at level 40.",
        keywords:["Ponyta"]},
    {
        _id:78.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/3/3f/078Rapidash.png/250px-078Rapidash.png",
        name:"Rapidash",
        type:"Fire",
        description:"Rapidash is a Fire-type Pokémon introduced in Generation I. It evolves from Ponyta starting at level 40.",
        keywords:["Rapidash"]},
    {
        _id:79.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/7/70/079Slowpoke.png/250px-079Slowpoke.png",
        name:"Slowpoke",
        type:"Water, Psychic",
        description:"Slowpoke (Japanese: ヤドン Yadon) is a dual-type Water/Psychic Pokémon introduced in Generation I. It evolves into Slowbro starting at level 37 or Slowking when traded holding a King's Rock.",
        keywords:["Slowpoke"]},
    {
        _id:80.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/8/80/080Slowbro.png/250px-080Slowbro.png",
        name:"Slowbro",
        type:"Water, Psychic",
        description:"Slowbro is a dual-type Water/Psychic Pokémon introduced in Generation I. It evolves from Slowpoke starting at level 37. It is one of Slowpoke's final forms, the other being Slowking. It can Mega Evolve into Mega Slowbro using the Slowbronite‎.",
        keywords:["Slowbro"]},
    {
        _id:81.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/6/6c/081Magnemite.png/250px-081Magnemite.png",
        name:"Magnemite",
        type:"Electric, Steel",
        description:"Magnemite is a dual-type Electric/Steel Pokémon introduced in Generation I. Prior to Generation II, it was a pure Electric-type Pokémon. It evolves into Magneton starting at level 30, which evolves into Magnezone when leveled up in a special magnetic field.",
        keywords:["Magnemite"]},
    {
        _id:82.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/7/72/082Magneton.png/250px-082Magneton.png",
        name:"Magneton",
        type:"Electric, Steel",
        description:"Magneton is a dual-type Electric/Steel Pokémon introduced in Generation I. Prior to Generation II, it was a pure Electric-type Pokémon. It evolves from Magnemite starting at level 30 and evolves into Magnezone when leveled up in a special magnetic field.",
        keywords:["Magneton"]},
    {
        _id:83.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/f/f8/083Farfetch%27d.png/250px-083Farfetch%27d.png",
        name:"Farfetch'd",
        type:"Normal, Flying",
        description:"Farfetch'd is a dual-type Normal/Flying Pokémon introduced in Generation I. It is not known to evolve into or from any other Pokémon.",
        keywords:["Farfetch'd","Farfetchd","Farfetch"]},
    {
        _id:84.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/5/54/084Doduo.png/250px-084Doduo.png",
        name:"Doduo",
        type:"Normal, Flying",
        description:"Doduo is a dual-type Normal/Flying Pokémon introduced in Generation I. It evolves into Dodrio starting at level 31.",
        keywords:["Doduo"]},
    {
        _id:85.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/9/93/085Dodrio.png/250px-085Dodrio.png",
        name:"Dodrio",
        type:"Normal, Flying",
        description:"Dodrio is a dual-type Normal/Flying Pokémon introduced in Generation I. It evolves from Doduo starting at level 31.",
        keywords:["Dodrio"]},
    {
        _id:86.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/1/1f/086Seel.png/250px-086Seel.png",
        name:"Seel",
        type:"Water",
        description:"Seel is a Water-type Pokémon introduced in Generation I. It evolves into Dewgong starting at level 34.",
        keywords:["Seel"]},
    {
        _id:87.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/c/c7/087Dewgong.png/250px-087Dewgong.png",
        name:"Dewgong",
        type:"Water, Ice",
        description:"Dewgong is a dual-type Water/Ice Pokémon introduced in Generation I. It evolves from Seel starting at level 34.",
        keywords:["Dewgong","Dilgong"]},
    {
        _id:88.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/a/a0/088Grimer.png/250px-088Grimer.png",
        name:"Grimer",
        type:"Poison",
        description:"Grimer (Japanese: ベトベター Betbeter) is a Poison-type Pokémon introduced in Generation I. It evolves into Muk starting at level 38. In Alola, Grimer has a regional variant that is Poison/Dark. It evolves into Alolan Muk starting at level 38.",
        keywords:["Grimer"]},
    {
        _id:89.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/7/7c/089Muk.png/250px-089Muk.png",
        name:"Muk",
        type:"Poison",
        description:"Muk is a Poison-type Pokémon introduced in Generation I. It evolves from Grimer starting at level 38. In Alola, Muk has a regional variant that is Poison/Dark. It evolves from Alolan Grimer starting at level 38.",
        keywords:["Muk"]},
    {
        _id:90.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/4/40/090Shellder.png/250px-090Shellder.png",
        name:"Shellder",
        type:"Water",
        description:"Shellder is a Water-type Pokémon introduced in Generation I. It evolves into Cloyster when exposed to a Water Stone.",
        keywords:["Shellder"]},
    {
        _id:91.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/1/1d/091Cloyster.png/250px-091Cloyster.png",
        name:"Cloyster",
        type:"Water, Ice",
        description:"Cloyster is a dual-type Water/Ice Pokémon introduced in Generation I. It evolves from Shellder when exposed to a Water Stone."
        ,keywords:["Cloyster"]},
    {
        _id:92.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/c/ca/092Gastly.png/250px-092Gastly.png",
        name:"Gastly",
        type:"Ghost, Poison",
        description:"Gastly is a dual-type Ghost/Poison Pokémon introduced in Generation I. It evolves into Haunter starting at level 25, which evolves into Gengar when traded.",
        keywords:["Gastly"]},
    {
        _id:93.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/6/62/093Haunter.png/250px-093Haunter.png",
        name:"Haunter",
        type:"Ghost, Poison",
        description:"Haunter is a dual-type Ghost/Poison Pokémon introduced in Generation I. It evolves from Gastly starting at level 25 and evolves into Gengar when traded.",
        keywords:["Haunter"]},
    {
        _id:94.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/c/c6/094Gengar.png/250px-094Gengar.png",
        name:"Gengar",
        type:"Ghost, Poison",
        description:"Gengar is a dual-type Ghost/Poison Pokémon introduced in Generation I. It evolves from Haunter when traded. It is the final form of Gastly. It can Mega Evolve into Mega Gengar using the Gengarite.",
        keywords:["Gengar"]},
    {
        _id:95.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/9/9a/095Onix.png/250px-095Onix.png",
        name:"Onix",
        type:"Rock, Ground",
        description:"Onix is a dual-type Rock/Ground Pokémon introduced in Generation I. It evolves into Steelix when traded holding a Metal Coat."
        ,keywords:["Onix"]},
    {
        _id:96.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/3/3e/096Drowzee.png/250px-096Drowzee.png",
        name:"Drowzee",
        type:"Psychic",
        description:"Drowzee is a Psychic-type Pokémon introduced in Generation I. It evolves into Hypno starting at level 26. ",
        keywords:["Drowzee","Peppa Pig","Peppa"]},
    {
        _id:97.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/0/0a/097Hypno.png/250px-097Hypno.png",
        name:"Hypno",
        type:"Psychic",
        description:"Hypno is a Psychic-type Pokémon introduced in Generation I. It evolves from Drowzee starting at level 26.",
        keywords:["Hypno"]},
    {
        _id:98.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/a/a7/098Krabby.png/250px-098Krabby.png",
        name:"Krabby",
        type:"Water",
        description:"Krabby is a Water-type Pokémon introduced in Generation I. It evolves into Kingler starting at level 28.",
        keywords:["Krabby"]},
    {
        _id:99.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/7/71/099Kingler.png/250px-099Kingler.png",
        name:"Kingler",
        type:"Water",
        description:"Kingler is a Water-type Pokémon introduced in Generation I. It evolves from Krabby starting at level 28.",
        keywords:["Kingler"]},
    {
        _id:100.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/d/da/100Voltorb.png/250px-100Voltorb.png",
        name:"Voltorb",
        type:"Electric",
        description:"Voltorb is an Electric-type Pokémon introduced in Generation I. It evolves into Electrode starting at level 30.",
        keywords:["Voltorb"]},
    {
        _id:101.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/8/84/101Electrode.png/250px-101Electrode.png",
        name:"Electrode",
        type:"Electric",
        description:"Electrode (Japanese: マルマイン Marumine) is an Electric-type Pokémon introduced in Generation I. It evolves from Voltorb starting at level 30.",
        keywords:["Electrode","Eletrode"]},
    {
        _id:102.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/a/af/102Exeggcute.png/250px-102Exeggcute.png",
        name:"Exeggcute",
        type:"Grass, Psychic",
        description:"Exeggcute is a dual-type Grass/Psychic Pokémon introduced in Generation I. It evolves into Exeggutor when exposed to a Leaf Stone. In Alola, Exeggcute will evolve into Alolan Exeggutor when exposed to a Leaf Stone.",
        keywords:["Exeggcute","Execute"]},
    {
        _id:103.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/2/24/103Exeggutor.png/250px-103Exeggutor.png",
        name:"Exeggutor",
        type:"Grass, Psychic",
        description:"Exeggutor is a dual-type Grass/Psychic Pokémon introduced in Generation I. It evolves from Exeggcute when exposed to a Leaf Stone. In Alola, Exeggutor has a regional variant that is Grass/Dragon. It evolves from Exeggcute when exposed to a Leaf Stone. All Exeggcute in Alola evolve into this form regardless of their origin.",
        keywords:["Exeggutor","Executor"]},
    {
        _id:104.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/2/2a/104Cubone.png/250px-104Cubone.png",
        name:"Cubone",
        type:"Ground",
        description:"Cubone (Japanese: カラカラ Karakara) is a Ground-type Pokémon introduced in Generation I. It evolves into Marowak starting at level 28. In Alola, Cubone will evolve into Alolan Marowak when leveled up at night starting at level 28.",
        keywords:["Cubone"]},
    {
        _id:105.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/9/98/105Marowak.png/250px-105Marowak.png",
        name:"Marowak",
        type:"Ground",
        description:"Marowak is a Ground-type Pokémon introduced in Generation I. It evolves from Cubone starting at level 28. In Alola, Marowak has a regional variant that is Fire/Ghost. It evolves from Cubone when leveled up at night starting at level 28. All Cubone in Alola evolve into this form regardless of their origin.",
        keywords:["Marowak"]},
    {
        _id:106.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/3/32/106Hitmonlee.png/250px-106Hitmonlee.png",
        name:"Hitmonlee",
        type:"Fighting",
        description:"Hitmonlee is a Fighting-type Pokémon introduced in Generation I. It evolves from Tyrogue starting at level 20 when Tyrogue's Attack is higher than its Defense. It is one of Tyrogue's final forms, the others being Hitmonchan and Hitmontop.",
        keywords:["Hitmonlee"]},
    {
        _id:107.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/a/a3/107Hitmonchan.png/250px-107Hitmonchan.png",
        name:"Hitmonchan",
        type:"Fighting",
        description:"Hitmonchan is a Fighting-type Pokémon introduced in Generation I. It evolves from Tyrogue starting at level 20 when Tyrogue's Defense is higher than its Attack. It is one of Tyrogue's final forms, the others being Hitmonlee and Hitmontop.",
        keywords:["Hitmonchan"]},
    {
        _id:108.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/0/00/108Lickitung.png/250px-108Lickitung.png",
        name:"Lickitung",
        type:"Normal",
        description:"Lickitung is a Normal-type Pokémon introduced in Generation I. Starting in Generation IV, it evolves into Lickilicky when leveled up while knowing Rollout.",
        keywords:["Lickitung"]},
    {
        _id:109.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/1/17/109Koffing.png/250px-109Koffing.png",
        name:"Koffing",
        type:"Poison",
        description:"Koffing (Japanese: ドガース Dogars) is a Poison-type Pokémon introduced in Generation I. It evolves into Weezing starting at level 35.",
        keywords:["Koffing"]},
    {
        _id:110.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/4/42/110Weezing.png/250px-110Weezing.png",
        name:"Weezing",
        type:"Poison",
        description:"Weezing is a Poison-type Pokémon introduced in Generation I. It evolves from Koffing starting at level 35.",
        keywords:["Weezing"]},
    {
        _id:111.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/9/9b/111Rhyhorn.png/250px-111Rhyhorn.png",
        name:"Rhyhorn",
        type:"Ground, Rock",
        description:"Rhyhorn is a dual-type Ground/Rock Pokémon introduced in Generation I. It evolves into Rhydon starting at level 42, which evolves into Rhyperior when traded holding a Protector.",
        keywords:["Rhyhorn"]},
    {
        _id:112.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/4/47/112Rhydon.png/250px-112Rhydon.png",
        name:"Rhydon",
        type:"Ground, Rock",
        description:"Rhydon is a dual-type Ground/Rock Pokémon introduced in Generation I. It evolves from Rhyhorn starting at level 42 and evolves into Rhyperior when traded holding a Protector.",
        keywords:["Rhydon"]},
    {
        _id:113.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/c/cd/113Chansey.png/250px-113Chansey.png",
        name:"Chansey",
        type:"Normal",
        description:"Chansey is a Normal-type Pokémon introduced in Generation I. It evolves from Happiny when leveled up holding an Oval Stone during the day and evolves into Blissey when leveled up with high friendship.",
        keywords:["Chansey"]},
    {
        _id:114.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/3/3e/114Tangela.png/250px-114Tangela.png",
        name:"Tangela",
        type:"Grass",
        description:"Tangela is a Grass-type Pokémon introduced in Generation I. It evolves into Tangrowth when leveled up while knowing Ancient Power.",
        keywords:["Tangela"]},
    {
        _id:115.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/4/4e/115Kangaskhan.png/250px-115Kangaskhan.png",
        name:"Kangaskhan",
        type:"Normal",
        description:"Kangaskhan is a Normal-type Pokémon introduced in Generation I. While it is not known to evolve into or from any other Pokémon, it can Mega Evolve into Mega Kangaskhan using the Kangaskhanite.",
        keywords:["Kangaskhan","Kangaskan"]},
    {
        _id:116.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/5/5a/116Horsea.png/250px-116Horsea.png",
        name:"Horsea",
        type:"Water",
        description:"Horsea is a Water-type Pokémon introduced in Generation I. It evolves into Seadra starting at level 32, which evolves into Kingdra when traded holding a Dragon Scale.",
        keywords:["Horsea"]},
    {
        _id:117.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/2/26/117Seadra.png/250px-117Seadra.png",
        name:"Seadra",
        type:"Water",
        description:"Seadra is a Water-type Pokémon introduced in Generation I. It evolves from Horsea starting at level 32 and evolves into Kingdra when traded holding a Dragon Scale.",
        keywords:["Seadra"]},
    {
        _id:118.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/7/7b/118Goldeen.png/250px-118Goldeen.png",
        name:"Goldeen",
        type:"Water",
        description:"Goldeen is a Water-type Pokémon introduced in Generation I. It evolves into Seaking starting at level 33.",
        keywords:["Goldeen"]},
    {
        _id:119.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/6/6a/119Seaking.png/250px-119Seaking.png",
        name:"Seaking",
        type:"Water",
        description:"Seaking is a Water-type Pokémon introduced in Generation I. It evolves from Goldeen starting at level 33.",
        keywords:["Seaking"]},
    {
        _id:120.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/4/4f/120Staryu.png/250px-120Staryu.png",
        name:"Staryu",
        type:"Water",
        description:"Staryu is a Water-type Pokémon introduced in Generation I. It evolves into Starmie when exposed to a Water Stone.",
        keywords:["Staryu"]},
    {
        _id:121.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/c/cd/121Starmie.png/250px-121Starmie.png",
        name:"Starmie",
        type:"Water, Psychic",
        description:"Starmie is a dual-type Water/Psychic Pokémon introduced in Generation I. It evolves from Staryu when exposed to a Water Stone."
        ,keywords:["Starmie"]},
    {
        _id:122.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/e/ec/122Mr._Mime.png/250px-122Mr._Mime.png",
        name:"Mr. Mime",
        type:"Psychic, Fairy",
        description:"Mr. Mime is a dual-type Psychic/Fairy Pokémon introduced in Generation I. Prior to Generation VI, it was a pure Psychic-type Pokémon. It evolves from Mime Jr. when leveled up while knowing Mimic.",
        keywords:["Mr. Mime","Mr Mime","Mister Mime"]},
    {
        _id:123.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/b/ba/123Scyther.png/250px-123Scyther.png",
        name:"Scyther",
        type:"Bug, Flying",
        description:"Scyther is a dual-type Bug/Flying Pokémon introduced in Generation I. It evolves into Scizor when traded holding a Metal Coat."
        ,keywords:["Scyther","Scyter","Sciter"]},
    {
        _id:124.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/7/7c/124Jynx.png/250px-124Jynx.png",
        name:"Jynx",
        type:"Ice, Psychic",
        description:"Jynx is a dual-type Ice/Psychic Pokémon introduced in Generation I. It evolves from Smoochum starting at level 30.",
        keywords:["Jynx","Jinx"]},
    {
        _id:125.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/d/de/125Electabuzz.png/250px-125Electabuzz.png",
        name:"Electabuzz",
        type:"Electric",
        description:"Electabuzz is an Electric-type Pokémon introduced in Generation I. It evolves from Elekid starting at level 30 and evolves into Electivire when traded holding an Electirizer.",
        keywords:["Electabuzz","Electabuz"]},
    {
        _id:126.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/8/8c/126Magmar.png/250px-126Magmar.png",
        name:"Magmar",
        type:"Fire",
        description:"Magmar is a Fire-type Pokémon introduced in Generation I. It evolves from Magby starting at level 30 and evolves into Magmortar when traded holding a Magmarizer.",
        keywords:["Magmar"]},
    {
        _id:127.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/7/71/127Pinsir.png/250px-127Pinsir.png",
        name:"Pinsir",
        type:"Bug",
        description:"Pinsir is a Bug-type Pokémon introduced in Generation I. While it is not known to evolve into or from any other Pokémon, it can Mega Evolve into Mega Pinsir using the Pinsirite.",
        keywords:["Pinsir"]},
    {
        _id:128.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/b/b8/128Tauros.png/250px-128Tauros.png",
        name:"Tauros",
        type:"Normal",
        description:"Tauros is a Normal-type Pokémon introduced in Generation I. It is not known to evolve into or from any other Pokémon, but it is considered to be a counterpart of Miltank.",
        keywords:["Tauros","Taurus"]},
    {
        _id:129.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/0/02/129Magikarp.png/250px-129Magikarp.png",
        name:"Magikarp",
        type:"Water",
        description:"Magikarp is a Water-type Pokémon introduced in Generation I. It evolves into Gyarados starting at level 20.",
        keywords:["Magikarp","Magicarpa"]},
    {
        _id:130.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/4/41/130Gyarados.png/250px-130Gyarados.png",
        name:"Gyarados",
        type:"Water, Flying",
        description:"Gyarados is a dual-type Water/Flying Pokémon introduced in Generation I. It evolves from Magikarp starting at level 20. It can Mega Evolve into Mega Gyarados using the Gyaradosite.",
        keywords:["Gyarados"]},
    {
        _id:131.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/a/ab/131Lapras.png/250px-131Lapras.png",
        name:"Lapras",
        type:"Water, Ice",
        description:"Lapras is a dual-type Water/Ice Pokémon introduced in Generation I. It is not known to evolve into or from any other Pokémon."
        ,keywords:["Lapras"]},
    {
        _id:132.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/3/36/132Ditto.png/250px-132Ditto.png",
        name:"Ditto",
        type:"Normal",
        description:"Ditto is a Normal-type Pokémon introduced in Generation I. It is not known to evolve into or from any other Pokémon. It can breed with any Pokémon other than the Pokémon in the Undiscovered group and itself, including some genderless Pokémon, to produce Eggs of the other's species.",
        keywords:["Ditto","Dito"]},
    {
        _id:133.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/e/e2/133Eevee.png/250px-133Eevee.png",
        name:"Eevee",
        type:"Normal",
        description:"Eevee is a Normal-type Pokémon introduced in Generation I. It evolves into one of eight different Pokémon through various methods: Vaporeon when exposed to a Water Stone. Jolteon when exposed to a Thunder Stone. Flareon when exposed to a Fire Stone. Espeon when leveled up with high friendship during the daytime, including morning (Generation II onward, excludes areas with a Moss Rock or Ice Rock), or when leveled up with high friendship with a Sun Shard in the Bag (Pokémon XD). Umbreon when leveled up with high friendship during the nighttime (Generation II onward, excludes areas with a Moss Rock or Ice Rock), or when leveled up with high friendship with a Moon Shard in the Bag (Pokémon XD). Leafeon when leveled up near a Moss Rock (Generation IV onward). Glaceon when leveled up near an Ice Rock (Generation IV onward). Sylveon when leveled up with a Fairy-type move and two levels of Affection (Generation VI onward, excludes areas with a Moss Rock or Ice Rock). Eevee is the game mascot and starter Pokémon in Pokémon: Let's Go, Eevee!, as well as for the main characters of Pokémon XD: Gale of Darkness and Pokémon Conquest. It is also the rival's starter Pokémon in Pokémon Yellow, although Professor Oak originally intended to give it to the player.",
        keywords:["Eevee","Evee","Eeve","Eve"]},
    {
        _id:134.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/f/fd/134Vaporeon.png/250px-134Vaporeon.png",
        name:"Vaporeon",
        type:"Water",
        description:"Vaporeon is a Water-type Pokémon introduced in Generation I. It evolves from Eevee when exposed to a Water Stone. It is one of Eevee's final forms, the others being Jolteon, Flareon, Espeon, Umbreon, Leafeon, Glaceon, and Sylveon.",
        keywords:["Water"]},
    {
        _id:135.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/b/bb/135Jolteon.png/250px-135Jolteon.png",
        name:"Jolteon",
        type:"Electric",
        description:"Jolteon is an Electric-type Pokémon introduced in Generation I. It evolves from Eevee when exposed to a Thunder Stone. It is one of Eevee's final forms, the others being Vaporeon, Flareon, Espeon, Umbreon, Leafeon, Glaceon, and Sylveon.",
        keywords:["Jolteon"]},
    {
        _id:136.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/d/dd/136Flareon.png/250px-136Flareon.png",
        name:"Flareon",
        type:"Fire",
        description:"Flareon is a Fire-type Pokémon introduced in Generation I. It evolves from Eevee when exposed to a Fire Stone. It is one of Eevee's final forms, the others being Vaporeon, Jolteon, Espeon, Umbreon, Leafeon, Glaceon, and Sylveon.",
        keywords:["Flareon"]},
    {
        _id:137.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/6/6b/137Porygon.png/250px-137Porygon.png",
        name:"Porygon",
        type:"Normal",
        description:"Porygon is a Normal-type Pokémon introduced in Generation I. It evolves into Porygon2 when traded holding an Up-Grade, which evolves into Porygon-Z when traded holding a Dubious Disc.",
        keywords:["Porygon","Porigon"]},
    {
        _id:138.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/7/79/138Omanyte.png/250px-138Omanyte.png",
        name:"Omanyte",
        type:"Rock, Water",
        description:"Omanyte is a dual-type Rock/Water Fossil Pokémon introduced in Generation I. It is resurrected from a Helix Fossil and evolves into Omastar starting at level 40.",
        keywords:["Omanyte","Omanite"]},
    {
        _id:139.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/4/43/139Omastar.png/250px-139Omastar.png",
        name:"Omastar",
        type:"Rock, Water",
        description:"Omastar is a dual-type Rock/Water Fossil Pokémon introduced in Generation I. It evolves from Omanyte starting at level 40, after it is revived from a Helix Fossil.",
        keywords:["Omastar"]},
    {
        _id:140.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/f/f9/140Kabuto.png/250px-140Kabuto.png",
        name:"Kabuto",
        type:"Rock, Water",
        description:"Kabuto is a dual-type Rock/Water Fossil Pokémon introduced in Generation I. It is resurrected from a Dome Fossil and evolves into Kabutops starting at level 40.",
        keywords:["Kabuto"]},
    {
        _id:141.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/2/29/141Kabutops.png/250px-141Kabutops.png",
        name:"Kabutops",
        type:"Rock, Water",
        description:"Kabutops is a dual-type Rock/Water Fossil Pokémon introduced in Generation I. It evolves from Kabuto starting at level 40, after it is revived from a Dome Fossil.",
        keywords:["Kabutops"]},
    {
        _id:142.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/e/e8/142Aerodactyl.png/250px-142Aerodactyl.png",
        name:"Aerodactyl",
        type:"Rock, Flying",
        description:"Aerodactyl is a dual-type Rock/Flying Fossil Pokémon introduced in Generation I. It is resurrected from an Old Amber, and while is not known to evolve into or from any other Pokémon, it can Mega Evolve into Mega Aerodactyl using the Aerodactylite.",
        keywords:["Aerodactyl","Aerodactil"]},
    {
        _id:143.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/f/fb/143Snorlax.png/250px-143Snorlax.png",
        name:"Snorlax",
        type:"Water, Ice",
        description:"Lapras is a dual-type Water/Ice Pokémon introduced in Generation I. It is not known to evolve into or from any other Pokémon."
        ,keywords:["Lapras"]},
    {
        _id:144.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/4/4e/144Articuno.png/250px-144Articuno.png",
        name:"Articuno",
        type:"Ice, Flying",
        description:"Articuno is a dual-type Ice/Flying Legendary Pokémon introduced in Generation I. It is not known to evolve into or from any other Pokémon. Along with Zapdos and Moltres, it is one of the three Legendary birds of Kanto.",
        keywords:["Articuno"]},
    {
        _id:145.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/e/e3/145Zapdos.png/250px-145Zapdos.png",
        name:"Zapdos",
        type:"Electric, Flying",
        description:"Zapdos is a dual-type Electric/Flying Legendary Pokémon introduced in Generation I. It is not known to evolve into or from any other Pokémon. Along with Articuno and Moltres, it is one of the three Legendary birds of Kanto.",
        keywords:["Zapdos"]},
    {
        _id:146.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/1/1b/146Moltres.png/250px-146Moltres.png",
        name:"Moltres",
        type:"Fire, Flying",
        description:"Moltres is a dual-type Fire/Flying Legendary Pokémon introduced in Generation I. It is not known to evolve into or from any other Pokémon. Along with Articuno and Zapdos, it is one of the three Legendary birds of Kanto.",
        keywords:["Moltres"]},
    {
        _id:147.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/c/cc/147Dratini.png/250px-147Dratini.png",
        name:"Dratini",
        type:"Dragon",
        description:"Dratini is a Dragon-type Pokémon introduced in Generation I. It evolves into Dragonair starting at level 30, which evolves into Dragonite starting at level 55.",
        keywords:["Dratini"]},
    {
        _id:148.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/9/93/148Dragonair.png/250px-148Dragonair.png",
        name:"Dragonair",
        type:"Dragon",
        description:"Dragonair is a Dragon-type Pokémon introduced in Generation I. It evolves from Dratini starting at level 30 and evolves into Dragonite starting at level 55.",
        keywords:["Dragonair"]},
    {
        _id:149.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/8/8b/149Dragonite.png/250px-149Dragonite.png",
        name:"Dragonite",
        type:"Dragon, Flying",
        description:"Dragonite is a dual-type Dragon/Flying pseudo-legendary Pokémon introduced in Generation I. It evolves from Dragonair starting at level 55. It is the final form of Dratini.",
        keywords:["Dragonite"]},
    {
        _id:150.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/7/78/150Mewtwo.png/250px-150Mewtwo.png",
        name:"Mewtwo",
        type:"Psychic",
        description:"Mewtwo is a Psychic-type Legendary Pokémon introduced in Generation I. While it is not known to evolve into or from any other Pokémon, it can Mega Evolve into two different forms: Mega Mewtwo X using Mewtwonite X and Mega Mewtwo Y using Mewtwonite Y. It is a member of the Mew duo along with Mew.",
        keywords:["Mewtwo","Milton"]},
    {
        _id:151.0,
        photo:"https://cdn.bulbagarden.net/upload/thumb/b/b1/151Mew.png/250px-151Mew.png",
        name:"Mew",
        type:"Psychic",
        description:"Mew is a Psychic-type Mythical Pokémon introduced in Generation I. It is not known to evolve into or from any other Pokémon. Mew is notable for its unique ability to learn every Technical Machine, Hidden Machine, and Move Tutor move (except those exclusive to a particular Pokémon or group of Pokémon, such as Draco Meteor and Secret Sword). Mew is the last Pokémon in the Kanto Pokédex. It is a member of the Mew duo along with Mewtwo.",
        keywords:["Mew"]}
]

module.exports = pokemonlist